const checklistItems = [
    // --- PRE-VIAJE ---
    { id: "R1", etapa: "pre-viaje", dimension: "Cognitiva / Pragmática", texto: "La información general de los servicios turísticos está disponible, es atractiva, detallada y está actualizada." },
    { id: "R2", etapa: "pre-viaje", dimension: "Pragmática", texto: "El prestador cuenta materiales promocionales digitales (redes sociales, página web) y/o físicos (folletos)" },
    { id: "R3", etapa: "pre-viaje", dimension: "Sensorial", texto: "Los materiales promocionales presentan un diseño intuitivo y visualmente atractivo." },
    { id: "R4", etapa: "pre-viaje", dimension: "Relacional", texto: "Están disponibles testimonios y reseñas de otros turistas" },
    { id: "R5", etapa: "pre-viaje", dimension: "Relacional", texto: "Existen canales para realizar preguntas previas y el prestador responde eficaz y oportunamente." },
    { id: "R6", etapa: "pre-viaje", dimension: "Pragmática", texto: "Se ofrecen opciones de servicios (alojamiento, comida, etc.) para diferentes presupuestos y preferencias." },
    { id: "R7", etapa: "pre-viaje", dimension: "Pragmática / Cognitiva", texto: "El proceso de reserva de servicios es sencillo, intuitivo y multicanal." },
    { id: "R8", etapa: "pre-viaje", dimension: "Pragmática", texto: "Se ofrecen políticas de cancelación claras y flexibles" },
    { id: "R9", etapa: "pre-viaje", dimension: "Cognitiva", texto: "Cuando el servicio y las condiciones de la zona lo requieren, se ofrecen sugerencias sobre vestimenta adecuada y/o costumbres locales." },
    { id: "R10", etapa: "pre-viaje", dimension: "Relacional", texto: "Los turistas reciben recordatorios o confirmaciones antes de la salida" },

    // --- DURANTE EL VIAJE ---
    { id: "R11", etapa: "durante-viaje", dimension: "Emocional / Cognitiva", texto: "Se advierten las condiciones físicas de caminos y accesos mediante algún medio de verificación anticipado (ej. avisos en redes sociales, correos o mensajes)." },
    { id: "R12", etapa: "durante-viaje", dimension: "Cognitiva", texto: "Se entrega información clara y oportuna sobre las alternativas de transporte o conectividad local disponibles." },
    { id: "R13", etapa: "durante-viaje", dimension: "Cognitiva", texto: "Se orienta al turista respecto a la logística de abastecimiento (combustible, provisiones, disponibilidad de efectivo/cajeros) considerando el aislamiento de la zona." },
    { id: "R14", etapa: "durante-viaje", dimension: "Pragmática / Cognitiva", texto: "Existen puntos de información turística que entregan información digital y/o en formato físico (offline)." },
    { id: "R15", etapa: "durante-viaje", dimension: "Emocional / Cognitiva", texto: "Se proporcionan pautas claras sobre procedimientos de emergencia y las instalaciones cuentan con planes de evacuación marcados." },
    { id: "R16", etapa: "durante-viaje", dimension: "Pragmática", texto: "Los alojamientos cuentan con servicios básicos garantizados (limpieza, Wifi, seguridad y agua potable todo el año)." },
    { id: "R17", etapa: "durante-viaje", dimension: "Cultura local", texto: "La oferta gastronómica incluye una variedad de opciones que reflejan la cultura y las tradiciones culinarias del destino." },
    { id: "R18", etapa: "durante-viaje", dimension: "Pragmática / Relacional", texto: "En caso de incluir alimentación, se ofrecen opciones adaptadas para personas con restricciones dietéticas (ej. vegetariana, celiaquía)." },
    { id: "R19", etapa: "durante-viaje", dimension: "Novedad / Cognitiva", texto: "El destino incluye una combinación equilibrada de atracciones naturales, culturales e históricas" },
    { id: "R20", etapa: "durante-viaje", dimension: "Cognitiva / Sostenibilidad", texto: "El prestador orienta o facilita información actualizada sobre los accesos, horarios y normativas de los atractivos consolidados de la zona, como Parques y Reservas Nacionales." },
    { id: "R21", etapa: "durante-viaje", dimension: "Sensorial", texto: "El entorno natural es visualmente atractivo y único" },
    { id: "R22", etapa: "durante-viaje", dimension: "Sensorial", texto: "Los accesos y el entorno físico del servicio presentan condiciones adecuadas de mantenimiento, señalización y aseo." },
    { id: "R23", etapa: "durante-viaje", dimension: "Pragmática / Sensorial", texto: "Los senderos están bien conservados y señalizados" },
    { id: "R24", etapa: "durante-viaje", dimension: "Pragmática", texto: "Las actividades disponibles en las atracciones se adaptan a diferentes edades y niveles de experiencia" },
    { id: "R25", etapa: "durante-viaje", dimension: "Emocional / Cognitiva", texto: "El servicio provee equipamiento físico de protección (ej. capas de agua, refugios) o planes de mitigación frente a condiciones climáticas que afecten la experiencia." },
    { id: "R26", etapa: "durante-viaje", dimension: "Cognitiva", texto: "Las actividades pueden ayudar al turista a aprender algo nuevo." },
    { id: "R27", etapa: "durante-viaje", dimension: "Sostenibilidad", texto: "Se promueve el respeto a la flora y fauna del lugar." },
    { id: "R28", etapa: "durante-viaje", dimension: "Sostenibilidad / Conductual", texto: "Se realizan actividades conservación y son comunicadas a los visitantes." },
    { id: "R29", etapa: "durante-viaje", dimension: "Sostenibilidad / Pragmática", texto: "Se gestiona el número de turistas para evitar la sobreexplotación del área." },
    { id: "R30", etapa: "durante-viaje", dimension: "Sostenibilidad", texto: "El destino implementa y promueve prácticas de sostenibilidad, reciclaje, uso consciente de recursos y energía renovable." },
    { id: "R31", etapa: "durante-viaje", dimension: "Relacional", texto: "Los proveedores de servicios y personal en general demuestran ser amables, atentos y profesionales." },
    { id: "R32", etapa: "durante-viaje", dimension: "Pragmática / Relacional", texto: "Se dispone de herramientas y recursos de traducción (guías, aplicaciones, señalización bilingüe/multilingüe)." },
    { id: "R33", etapa: "durante-viaje", dimension: "Cultura local", texto: "Se promueven actividades que reflejen las tradiciones y los valores culturales de la comunidad." },
    { id: "R34", etapa: "durante-viaje", dimension: "Relacional", texto: "La diversidad cultural se celebra y se respeta en las experiencias que se ofrecen." },
    { id: "R35", etapa: "durante-viaje", dimension: "Relacional / Cultura local", texto: "Los prestadores promueven interacciones culturales auténticas con la población local." },
    { id: "R36", etapa: "durante-viaje", dimension: "Novedad / Emocional", texto: "El entorno y el servicio integran elementos que propician la sensación de novedad y desconexión de la rutina." },
    { id: "R37", etapa: "durante-viaje", dimension: "Emocional", texto: "El servicio provee espacios o momentos libres de estrés que favorecen el descanso mental y la recarga de energías." },

    // --- POST-VIAJE ---
    { id: "R38", etapa: "post-viaje", dimension: "Relacional", texto: "Se proporciona un canal claro y efectivo (ej. Teléfono, web o WhatsApp) para abordar asuntos pendientes (ej. facturación, reembolsos)." },
    { id: "R39", etapa: "post-viaje", dimension: "Relacional", texto: "El prestador cuenta con un protocolo o sistema para el seguimiento y fidelización post-viaje (ej. mensaje de agradecimiento)." },
    { id: "R40", etapa: "post-viaje", dimension: "Conductual", texto: "Se brindan oportunidades a los turistas para compartir comentarios o calificar los servicios." },
    { id: "R41", etapa: "post-viaje", dimension: "Relacional / Pragmática", texto: "Se tiene en cuenta los comentarios de los clientes para mejorar." },
    { id: "R42", etapa: "post-viaje", dimension: "Emocional", texto: "El servicio cumple lo que prometió en sus materiales promocionales." },
    { id: "R43", etapa: "post-viaje", dimension: "Cognitiva / Emocional", texto: "La relación precio/calidad del servicio prestado es coherente." }
];
